server:
  port: ${PORT:6969}
spring:
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  messages:
    basename: i18n/messages
    encoding: utf-8
  data:
    mongodb:
      uri: ${URI_MONGODB}
api:
  version1: api/v1
jwt:
  expiration: 604800 # 7 days
  secret-key: ${JWT_SECRET_KEY}
cloud:
  aws:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
    region: ${AWS_REGION}
    bucket-name: ${AWS_BUCKET_NAME}
mail:
  host: smtp.gmail.com
  port: 587
  username: ${EMAIL_USER_NAME}
  password: ${EMAIL_PASSWORD}